// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/izinga/robustest-web/internal/app/views/layouts"

func LegalPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Hero Section --> <section class=\"pt-28 bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 text-white py-16\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><div class=\"max-w-3xl\"><h1 class=\"text-4xl md:text-5xl font-bold\">Privacy & Terms</h1></div></div></section><!-- Content --> <section class=\"py-16 bg-white\"><div class=\"max-w-3xl mx-auto px-4 sm:px-6 lg:px-8\"><!-- Privacy Policy --><div class=\"mb-12\"><h2 class=\"text-2xl font-bold text-gray-900 mb-4\">Privacy Policy</h2><div class=\"space-y-4 text-gray-600\"><p>RobusTest collects basic contact information (name, email, company) when you reach out to us. We use this solely to respond to your inquiries and provide product information.</p><p><strong>Your test data stays with you.</strong> RobusTest is an on-premise solution—all your testing data remains on your infrastructure.</p><p>We use SendGrid for email delivery. For questions, contact us at <a href=\"mailto:hello@robustest.com\" class=\"text-cyan-600 hover:underline\">hello@robustest.com</a>.</p></div></div><!-- Terms of Service --><div><h2 class=\"text-2xl font-bold text-gray-900 mb-4\">Terms of Service</h2><div class=\"space-y-4 text-gray-600\"><p>By using robustest.com, you agree to these terms. RobusTest provides on-premise mobile device lab management software for enterprises.</p><p>All content, trademarks, and software on this website are property of Izinga. Use our services lawfully and do not attempt unauthorized access to our systems.</p><p>These terms are governed by the laws of India. For questions, contact <a href=\"mailto:hello@robustest.com\" class=\"text-cyan-600 hover:underline\">hello@robustest.com</a>.</p></div></div></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.Base("Privacy & Terms", "Privacy Policy and Terms of Service for RobusTest enterprise mobile device lab platform.", "/legal").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
